# Generated by Django 3.2.18 on 2023-05-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azon', models.IntegerField()),
                ('nev', models.CharField(max_length=64)),
                ('terulet', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Tudós',
                'verbose_name_plural': 'Tudosok',
            },
        ),
        migrations.CreateModel(
            name='Eloadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azon', models.IntegerField()),
                ('cim', models.CharField(max_length=256)),
                ('ido', models.DateField()),
                ('tudosok', models.ManyToManyField(to='app_default.Tudos')),
            ],
            options={
                'verbose_name': 'Előadás',
                'verbose_name_plural': 'Előadások',
            },
        ),
    ]
